name: Release
run-name: Release ${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version X.X.X'
        required: true
        type: string
jobs:
  run:
    if: github.ref == github.event.repository.default_branch
    uses: ./.github/workflows/ci.yaml
    secrets: inherit
    with:
      version: ${{ inputs.version }}
